#!/bin/bash
echo '====================================================' >> /var/log/update_script.log
echo "updates of $(date)" >> /var/log/update_script.log
echo '====================================================' >> /var/log/update_script.log
sudo apt -y update >> /var/log/update_script.log 
echo '====================================================' >> /var/log/update_script.log
echo "upgrades of $(date)" >> /var/log/update_script.log
echo '====================================================' >> /var/log/update_script.log
sudo apt -y upgrade >> /var/log/update_script.log 
