#!/bin/bash

FILE="/var/tmp/checksum"
FILE_TO_WATCH="/etc/crontab"
MD5VALUE=$(sudo md5sum $FILE_TO_WATCH)

if [ ! -f $FILE ]
then
		 echo "$MD5VALUE" > $FILE
		 	 exit 0;
		 fi;

		 if [ "$MD5VALUE" != "$(cat $FILE)" ];
			 	then
						echo "$MD5VALUE" > $FILE
							echo "$FILE_TO_WATCH has been modified " | mail -s "$FILE_TO_WATCH modified !" saadelyousfi95@gmail.com,root
						fi;
